# Generated by Django 5.1.2 on 2025-03-06 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='faculty',
            field=models.CharField(default='CSIT', max_length=200),
            preserve_default=False,
        ),
    ]
