# Generated by Django 5.1.3 on 2025-03-17 22:07

from django.db import migrations
from functools import partial

def create_initial_data(apps, schema_editor, model, data):
    model = apps.get_model('main', model)

    for instance in data:
        model.objects.create(**instance)

def setup_admin(apps, schema_editor):
    Admin = apps.get_model('main', 'Admin')

    for usr in [f'o5-{i}' for i in range(0, 9)]:
        adm = Admin.objects.create(username='o5-1', person_type='A', department='IT')
        adm.set_password('TheSCPFoundation')
        adm.is_staff = adm.is_superuser = True
        adm.save()

colleges = [
    {'code': 'csit', 'name': 'Computer Science and Information Technology Program', 'description': 'desc.'},
    {'code': 'foe', 'name': 'Faculty of Engineering', 'description': 'desc.'},
]

faculties = [
    {'code': 'csit-csc', 'college_id': 'csit', 'name': 'Computer Science', 'description': 'desc.'},
    {'code': 'csit-aid', 'college_id': 'csit', 'name': 'Artificial Intelligence and Data Science', 'description': 'desc.'},
    {'code': 'csit-cnc', 'college_id': 'csit', 'name': 'Computer Networks and Cyber Security', 'description': 'desc.'},
    {'code': 'csit-bif', 'college_id': 'csit', 'name': 'Bioinformatics', 'description': 'desc.'},

    {'code': 'foe-ecce', 'college_id': 'foe', 'name': 'School of Electronics, Communications and Computer Engineering', 'description': 'desc.'},
    {'code': 'foe-eece', 'college_id': 'foe', 'name': 'School of Energy Resources, Environmental, Chemical and Petrochemical Engineering', 'description': 'desc.'},
    {'code': 'foe-ide', 'college_id': 'foe', 'name': 'School of Innovative Design Engineering', 'description': 'desc.'},
    {'code': 'foe-bas', 'college_id': 'foe', 'name': 'Institute of Basic and Applied Science', 'description': 'desc.'},
]

professors = [
    {'faculty_id': 'csit-csc', 'username': 'csit_csc_prof1', 'first_name': 'Test', 'last_name': 'Prof1',  'email': 'csit_csc_prof1@example.com'},
    {'faculty_id': 'csit-csc', 'username': 'csit_csc_prof2', 'first_name': 'Test', 'last_name': 'Prof2',  'email': 'csit_csc_prof2@example.com'},
    {'faculty_id': 'csit-csc', 'username': 'csit_csc_prof3', 'first_name': 'Test', 'last_name': 'Prof3',  'email': 'csit_csc_prof3@example.com'},
    {'faculty_id': 'csit-csc', 'username': 'csit_csc_prof4', 'first_name': 'Test', 'last_name': 'Prof4',  'email': 'csit_csc_prof4@example.com'},
    {'faculty_id': 'csit-aid', 'username': 'csit_aid_prof1', 'first_name': 'Test', 'last_name': 'Prof5',  'email': 'csit_aid_prof1@example.com'},
    {'faculty_id': 'csit-aid', 'username': 'csit_aid_prof2', 'first_name': 'Test', 'last_name': 'Prof6',  'email': 'csit_aid_prof2@example.com'},
    {'faculty_id': 'csit-aid', 'username': 'csit_aid_prof3', 'first_name': 'Test', 'last_name': 'Prof7',  'email': 'csit_aid_prof3@example.com'},
    {'faculty_id': 'csit-aid', 'username': 'csit_aid_prof4', 'first_name': 'Test', 'last_name': 'Prof8',  'email': 'csit_aid_prof4@example.com'},
    {'faculty_id': 'csit-cnc', 'username': 'csit_cnc_prof1', 'first_name': 'Test', 'last_name': 'Prof9',  'email': 'csit_cnc_prof1@example.com'},
    {'faculty_id': 'csit-cnc', 'username': 'csit_cnc_prof2', 'first_name': 'Test', 'last_name': 'Prof10', 'email': 'csit_cnc_prof2@example.com'},
    {'faculty_id': 'csit-cnc', 'username': 'csit_cnc_prof3', 'first_name': 'Test', 'last_name': 'Prof11', 'email': 'csit_cnc_prof3@example.com'},
    {'faculty_id': 'csit-cnc', 'username': 'csit_cnc_prof4', 'first_name': 'Test', 'last_name': 'Prof12', 'email': 'csit_cnc_prof4@example.com'},
    {'faculty_id': 'csit-bif', 'username': 'csit_bif_prof1', 'first_name': 'Test', 'last_name': 'Prof13', 'email': 'csit_bif_prof1@example.com'},
    {'faculty_id': 'csit-bif', 'username': 'csit_bif_prof2', 'first_name': 'Test', 'last_name': 'Prof14', 'email': 'csit_bif_prof2@example.com'},
    {'faculty_id': 'csit-bif', 'username': 'csit_bif_prof3', 'first_name': 'Test', 'last_name': 'Prof15', 'email': 'csit_bif_prof3@example.com'},
    {'faculty_id': 'csit-bif', 'username': 'csit_bif_prof4', 'first_name': 'Test', 'last_name': 'Prof16', 'email': 'csit_bif_prof4@example.com'},
]

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(setup_admin),
        migrations.RunPython(partial(create_initial_data, model='College', data=colleges)),
        migrations.RunPython(partial(create_initial_data, model='Faculty', data=faculties)),
        migrations.RunPython(partial(create_initial_data, model='Professor', data=professors)),
    ]
