# Generated by Django 5.1.2 on 2024-12-09 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='username',
            field=models.CharField(default='320', max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
