# Generated by Django 5.1.2 on 2025-03-06 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_person_faculty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='faculty',
        ),
        migrations.AddField(
            model_name='graduationproject',
            name='year',
            field=models.IntegerField(default=2025),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professor',
            name='faculty',
            field=models.CharField(default='CSIT', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='faculty',
            field=models.CharField(default='CSIT', max_length=200),
            preserve_default=False,
        ),
    ]
