# Generated by Django 5.1.3 on 2025-03-23 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('kind', models.CharField(choices=[('o', 'Online Meeting'), ('a', 'Assignment'), ('q', 'Quiz')], default='a', max_length=1)),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.classroom')),
            ],
        ),
        migrations.RemoveField(
            model_name='assignmentsubmission',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='classroom',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='description',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='id',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='title',
        ),
        migrations.AddField(
            model_name='assignment',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.assignment'),
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.task')),
                ('max_grade', models.IntegerField(blank=True, null=True)),
                ('questions', models.JSONField()),
            ],
            bases=('main.task',),
        ),
        migrations.AddField(
            model_name='assignment',
            name='task_ptr',
            field=models.OneToOneField(auto_created=True, default=-1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.task'),
            preserve_default=False,
        ),
    ]
