# Generated by Django 5.1.2 on 2025-03-06 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_person_faculty_graduationproject_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='graduationproject',
            name='faculty',
            field=models.CharField(default='CSIT', max_length=200),
            preserve_default=False,
        ),
    ]
