# Generated by Django 5.1.2 on 2025-04-27 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_task_remove_assignment_classroom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='main.professor'),
        ),
        migrations.AlterField(
            model_name='college',
            name='code',
            field=models.CharField(max_length=5, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='code',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
