# Generated by Django 5.1.3 on 2025-03-22 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_college_code_alter_enrollment_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='classroom',
        ),
        migrations.AlterField(
            model_name='material',
            name='material_type',
            field=models.CharField(choices=[('l', 'Lab'), ('L', 'Lecture'), ('t', 'Tutorial'), ('a', 'Assignment'), ('s', 'Problem Sheet'), ('o', 'Other')], default='o', max_length=1),
        ),
    ]
