# Generated by Django 5.1.3 on 2025-05-18 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_task_remove_assignment_classroom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='person',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='event_registrations', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='eventregistration',
            unique_together={('event', 'person')},
        ),
        migrations.AlterField(
            model_name='college',
            name='code',
            field=models.CharField(max_length=5, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='code',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.RemoveField(
            model_name='eventregistration',
            name='student',
        ),
    ]
