# Generated by Django 5.1.3 on 2025-05-22 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_eventregistration_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='material_type',
            new_name='kind',
        ),
        migrations.AlterField(
            model_name='material',
            name='kind',
            field=models.CharField(choices=[('l', 'Lab'), ('L', 'Lecture'), ('t', 'Tutorial'), ('a', 'Assignment'), ('s', 'Problem Sheet'), ('o', 'Other')], default='o', max_length=1),
            preserve_default=False,
        ),
    ]
