# Generated by Django 5.1.3 on 2025-04-28 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_material_created_by_alter_college_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='college',
        ),
        migrations.RemoveField(
            model_name='course',
            name='level',
        ),
        migrations.RemoveField(
            model_name='course',
            name='semester_kind',
        ),
        migrations.AddField(
            model_name='course',
            name='prof',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='main.professor'),
        ),
    ]
