# Generated by Django 5.1.3 on 2025-04-28 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_course_college_remove_course_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='college',
            field=models.ForeignKey(default='csit', on_delete=django.db.models.deletion.CASCADE, to='main.college'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], default=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='semester_kind',
            field=models.CharField(choices=[('F', 'Fall'), ('S', 'Spring'), ('s', 'Summer')], default='F', max_length=1),
            preserve_default=False,
        ),
    ]
