# Generated by Django 5.1.3 on 2025-06-10 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_material_material_type_material_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wedensday'), (4, 'Thursday')])),
                ('slot', models.IntegerField(choices=[(0, 'Period 1 Half 1'), (1, 'Period 1 Half 2'), (2, 'Period 2 Half 1'), (3, 'Period 2 Half 2'), (4, 'Period 3 Half 1'), (5, 'Period 3 Half 2'), (6, 'Period 4 Half 1'), (7, 'Period 4 Half 2')])),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.professor')),
            ],
        ),
    ]
