# Generated by Django 5.1.3 on 2025-05-05 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_course_college_course_level_course_semester_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='teaching_assistants',
            field=models.ManyToManyField(blank=True, related_name='classrooms', to='main.teachingassistant'),
        ),
    ]
